### ISSUE TITLE
Coming String provided into the Text widget does not wrap as the normally hardcoded String.

### ISSUE THREAD

**Issue by lebkovy** [smartnsoft/FlappyTranslator#6]
The String I set in my CSV file comes by calling I18n.of(context).noEmail but it is cut in the middle of one word and the rest is in the new line. It should wrap the text, and move whole word as it is when I hardcoded String and display it i the same place.

I did some tests with two the same Strings - one from I18n.of(context).noEmail and the second one I hardcoded in my Widget, so it's the same two Strings. When I want to display it in normal Text Widget the first one is not wrapped by contrast to the second one.

**Comment by defuncart** [comment]
Have you checked to see if your string contains a no break space (\u+00A0)? I had this issue when I created a CSV file from an Excel spreadsheet, there were many no break spaces instead of normal spaces, thus forcing word splitting at strange positions etc.  Using VSCode or some other code editor, you can use change how whitespace is rendered and check if your CSV text is correctly formatted.

If that doesn't help, please post an reproducible issue here.

**Comment by lebkovy** [comment]
Cool, I'll check it as soon as possible and I'll be back to report what happened. Thanks :)

**Comment by lebkovy** [comment]
I've went through your hints and finally it worked. I had to convert no break spaces by calling replaceAll(new RegExp('\u00A0'), ' ') on my coming String. Thank you a lot :)

**Comment by defuncart** [comment]
Proszę Jakub. As this seems to be something that may also effect others, I've created this PR: https://github.com/smartnsoft/FlappyTranslator/pull/7
