### ISSUE TITLE
Why to use depend_on_context?

### ISSUE THREAD

**Issue by akalitenya** [smartnsoft/FlappyTranslator#9]
Hi. Can you explain why to use depend_on_context: True (pros/cons)? And how to use library when this option is set to False?

**Comment by ThomasEcalle** [comment]
Hi !

The fact that most of packages about internationalisation depend on context has been a real discussion on StackOverflow because it is a real issue when you want to access your Strings without having the context.

You can find the discussion here : https://github.com/flutter/flutter/issues/14518

To be honest, at first, I have made the package using BuildContext without real reason except that I thought it was mandatory.

But @defuncart did mention the discussion I have just linked and the fact that the package do not have to rely on Context to work perfectly : https://github.com/smartnsoft/FlappyTranslator/pull/3

So, to answer your question :

* In both cases, switching your language in settings (while the app is running) will successfully re-render your app with the correct strings

* When you set `depend_on_context` to `false`, here is how to access a  `title` for exemple : 

`I18n.appTitle`    (more simple, no ?)

* There is no real cons setting  `depend_on_context` to `false` !
I just keep the possibility to put it to `true` for the people who already used it :)

Do not hesitate if you have other question or if you want me to be more specific :)

**Comment by akalitenya** [comment]
Thanks for the answer and this package! I think that you should add this to readme. I switched from another library. Integration was super smooth!
